# Generated by Django 3.1.3 on 2022-11-28 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('20100000', '서울특별시'), ('20120000', '강남구'), ('20112000', '강동구'), ('20103000', '강북구'), ('20110000', '강서구'), ('20124000', '관악구'), ('20113000', '광진구'), ('20123000', '구로구'), ('20125000', '금천구'), ('20102000', '노원구'), ('20101000', '도봉구'), ('20109000', '동대문구'), ('20122000', '동작구'), ('20111000', '마포구'), ('20108000', '서대문구'), ('20121000', '서초구'), ('20114000', '성동구'), ('20105000', '성북구'), ('20119000', '송파구'), ('20118000', '양천구'), ('20116000', '영등포구'), ('20117000', '용산구'), ('20104000', '은평구'), ('20106000', '종로구'), ('20115000', '중구'), ('20107000', '중랑구')], default='20122000', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=1000)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '커뮤니티',
                'verbose_name_plural': '커뮤니티',
                'db_table': 'tb_mainboard',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.mainboard')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
                'db_table': 'tb_reply',
            },
        ),
    ]
