# Generated by Django 3.1.3 on 2022-11-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('20100000', '서울전체'), ('20120000', '강남'), ('20112000', '강동'), ('20103000', '강북'), ('20110000', '강서'), ('20124000', '관악'), ('20113000', '광진'), ('20123000', '구로'), ('20125000', '금천'), ('20102000', '노원'), ('20101000', '도봉'), ('20109000', '동대문'), ('20122000', '동작'), ('20111000', '마포'), ('20108000', '서대문'), ('20121000', '서초'), ('20114000', '성동'), ('20105000', '성북'), ('20119000', '송파'), ('20118000', '양천'), ('20116000', '영등포'), ('20117000', '용산'), ('20104000', '은평'), ('20106000', '종로'), ('20115000', '중구'), ('20107000', '중랑')], default='20122000', max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=1000)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '커뮤니티',
                'verbose_name_plural': '커뮤니티',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.mainboard')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글',
            },
        ),
    ]
