# Generated by Django 3.1.3 on 2022-11-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TbEntArea',
        ),
    ]
