# Generated by Django 3.1.3 on 2022-11-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMainboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'community_mainboard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'community_reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThSearch',
            fields=[
                ('ht_num', models.AutoField(db_column='HT_NUM', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('recipe_nm', models.CharField(db_column='RECIPE_NM', max_length=50)),
                ('irdnt_nm', models.CharField(db_column='IRDNT_NM', max_length=50)),
                ('gd_nm', models.CharField(db_column='GD_NM', max_length=100)),
                ('ht_date', models.DateTimeField(blank=True, db_column='HT_DATE', null=True)),
            ],
            options={
                'db_table': 'th_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSecinquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquirys_name', models.CharField(max_length=20)),
                ('inquirys_email', models.CharField(max_length=30)),
                ('inquirys_text', models.TextField()),
            ],
            options={
                'db_table': 'user_secinquiry',
                'managed': False,
            },
        ),
    ]
